# Webhook Telegram Alert

This n8n workflow sends a Telegram message whenever a webhook endpoint is triggered.

It is useful as a lightweight alerting flow for testing webhooks, uptime checks, external system pings, or simple event notifications.

## What It Does

The workflow has 2 nodes:

1. `Webhook`
2. `Telegram`

Flow:

- A request hits the webhook path `telegram-test`
- n8n receives the request
- A Telegram message is sent to the configured chat
- The message includes the time the webhook was triggered

## Message Sent

The Telegram node sends this message:

```text
Webhook triggered at {{$now}}
```

## Requirements

Before using this workflow, make sure you have:

- An n8n instance
- A Telegram bot
- Telegram credentials configured in n8n
- A Telegram chat or group ID where messages should be sent

## Workflow Details

- Workflow name: `Webhook Telegram Alert`
- Webhook path: `telegram-test`
- Trigger type: `Webhook`
- Action: `Send a text message` via Telegram
- Status: `Active`

## Setup

1. Import the workflow JSON into n8n.
2. Open the `Send a text message` node.
3. Replace the Telegram credentials if needed.
4. Update the `chatId` to your own Telegram chat or group.
5. Save and activate the workflow.
6. Copy the webhook URL generated by your n8n instance.

## Example

If your n8n base URL is:

```text
https://your-n8n-domain.com
```

Then the webhook endpoint will look similar to:

```text
https://your-n8n-domain.com/webhook/telegram-test
```

You can test it with:

```bash
curl -X GET "https://your-n8n-domain.com/webhook/telegram-test"
```

After the request is received, your Telegram chat should get a message with the webhook trigger time.

## Use Cases

- Webhook connectivity testing
- Basic monitoring alerts
- External app event notifications
- Quick Telegram-based status pings

## Notes

- The current workflow sends alerts to a fixed chat ID.
- The message text can be customized in the Telegram node.
- You can extend this workflow by passing webhook data into the Telegram message.

## Security Reminder

If you plan to publish this workflow publicly:

- Remove or replace real chat IDs
- Reconnect your own Telegram credentials after import
- Avoid exposing production webhook URLs unless needed

## File

Source workflow:

- `Webhook Telegram Alert.json`
